services:
  tex:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 5173:5173
    environment:
      - INPUT_ROOT_FILE=main.tex
      - INPUT_CONTINUE_ON_ERROR=true
      - TMP_DIR=/tmp
    volumes:
      - ./tmp:/tmp
      - ./src:/app/src
