services:
  tex:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INPUT_ROOT_FILE=main.tex
      - INPUT_WORKING_DIRECTORY=/input
      # - INPUT_WORK_IN_ROOT_FILE_DIR
      # - INPUT_CONTINUE_ON_ERROR
      # - INPUT_ARGS
      # - INPUT_EXTRA_FONTS
    volumes:
      - ./input:/input
      - /var/run/docker.sock:/var/run/docker.sock
